(function(){
const css=`<style id="profGruposCss">
#grupos table{min-width:980px}.group-main-row{cursor:pointer}.group-main-row:hover{background:#f8fbfc}.group-name-link{font-weight:900;color:var(--navy);text-decoration:underline;text-decoration-style:dotted;text-underline-offset:3px}.group-actions{display:flex;gap:6px;flex-wrap:wrap}.group-actions .btn{font-size:.7rem;padding:7px 9px}.btn.details{background:#275f78}.btn.delete{background:#fff;color:#9b2c2c;border:1px solid #dca7a7}.group-detail-row td{background:#f8fbfc;padding:0!important;border-bottom:1px solid var(--line)}.group-detail{display:none;padding:14px 16px}.group-detail.open{display:block}.group-stage-list{display:grid;grid-template-columns:repeat(2,minmax(260px,1fr));gap:7px}.group-stage-item{display:flex;justify-content:space-between;gap:12px;align-items:center;border:1px solid var(--line);border-radius:9px;background:#fff;padding:8px 10px}.group-stage-item b{font-size:.75rem;color:#294754}.group-stage-status{font-size:.66rem;font-weight:900;border-radius:999px;padding:4px 7px;background:#eef3f5;white-space:nowrap}.group-stage-status.ok{background:#e7f4ed;color:#2d7757}.group-stage-status.info{background:#e8f1f5;color:#275f78}.group-stage-status.danger{background:#fff0ef;color:#9b2c2c}.group-stage-status.warn{background:#fff1c6;color:#8b6100}.group-progress{font-weight:900;color:var(--navy)}@media(max-width:760px){.group-stage-list{grid-template-columns:1fr}}
</style>`;
if(!document.getElementById('profGruposCss'))document.head.insertAdjacentHTML('beforeend',css);
const clean=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function cls(s){s=String(s||'').toUpperCase();if(/CONCLU|APROV/.test(s))return'ok';if(/ANÁLISE|ANALISE/.test(s))return'info';if(/CORRIG|ATRAS/.test(s))return'danger';return'warn'}
async function loadStageMap(){const [{data:ges,error:gErr},{data:eps,error:eErr}]=await Promise.all([sb.from('grupo_etapas').select('grupo_id,etapa_id,status,percentual').order('created_at'),sb.from('etapas').select('id,nome,ordem').order('ordem')]);if(gErr)throw gErr;if(eErr)throw eErr;const ep=new Map((eps||[]).map(x=>[x.id,x])),map={};(ges||[]).forEach(x=>{(map[x.grupo_id]||(map[x.grupo_id]=[])).push({...x,etapa:ep.get(x.etapa_id)})});Object.values(map).forEach(a=>a.sort((x,y)=>(x.etapa?.ordem||0)-(y.etapa?.ordem||0)));return map}
async function removePaths(paths){const unique=[...new Set(paths.filter(Boolean))];for(let i=0;i<unique.length;i+=100){const {error}=await sb.storage.from('ptcc-arquivos').remove(unique.slice(i,i+100));if(error)throw error}}
async function deleteGroup(g){if(!confirm(`Excluir definitivamente o grupo ${g.codigo} — ${g.nome}?\n\nSerão apagados entregas, devolutivas e arquivos vinculados.`))return;const code=prompt('Digite o código do grupo para confirmar:');if(String(code||'').trim().toUpperCase()!==String(g.codigo||'').toUpperCase())return;try{const [{data:a,error:ae},{data:s,error:se}]=await Promise.all([sb.from('arquivos').select('caminho_storage').eq('grupo_id',g.id),sb.from('solicitacoes_grupo').select('caminho_termo_original,caminho_termo_assinado,caminho_termo').eq('grupo_id',g.id)]);if(ae||se)throw(ae||se);const paths=[...(a||[]).map(x=>x.caminho_storage),...(s||[]).flatMap(x=>[x.caminho_termo_original,x.caminho_termo_assinado||x.caminho_termo])];await removePaths(paths);const {error}=await sb.rpc('professor_excluir_grupo',{p_grupo_id:g.id});if(error)throw error;alert('Grupo excluído com sucesso.');await loadAll()}catch(e){alert(e.message||'Não foi possível excluir o grupo.')}}
window.excluirGrupoPTCC=deleteGroup;
async function renderEnhanced(rows){const body=document.getElementById('grpBody');if(!body)return;const table=body.closest('table'),head=table?.querySelector('thead tr');if(head)head.innerHTML='<th>Código</th><th>Grupo</th><th>Tema</th><th>Status</th><th>Progresso</th><th>Ações</th>';if(!rows?.length){body.innerHTML='<tr><td colspan="6" class="empty">Nenhum grupo validado.</td></tr>';return}const stageMap=await loadStageMap();body.innerHTML='';rows.forEach(g=>{const main=document.createElement('tr');main.className='group-main-row';main.innerHTML=`<td><b>${clean(g.codigo||'—')}</b></td><td><span class="group-name-link">${clean(g.nome||'—')}</span></td><td>${clean(g.tema||'—')}</td><td><span class="chip ${typeof chip==='function'?chip(g.status):''}">${clean(g.status||'—')}</span></td><td><span class="group-progress">${g.progresso||0}%</span></td><td><div class="group-actions"><button class="btn details" type="button">Ver etapas</button><button class="btn delete" type="button">Excluir grupo</button></div></td>`;const detail=document.createElement('tr');detail.className='group-detail-row';const arr=stageMap[g.id]||[];detail.innerHTML=`<td colspan="6"><div class="group-detail"><div class="group-stage-list">${arr.length?arr.map(x=>`<div class="group-stage-item"><b>${clean(x.etapa?.nome||'Etapa')}</b><span class="group-stage-status ${cls(x.status)}">${clean(x.status||'—')}</span></div>`).join(''):'<span class="sub">Nenhuma etapa vinculada.</span>'}</div></div></td>`;body.append(main,detail);const panel=detail.querySelector('.group-detail'),btn=main.querySelector('.details');const toggle=()=>{const open=panel.classList.toggle('open');btn.textContent=open?'Recolher etapas':'Ver etapas'};main.querySelector('.group-name-link').onclick=e=>{e.stopPropagation();toggle()};btn.onclick=e=>{e.stopPropagation();toggle()};main.onclick=e=>{if(e.target.closest('button'))return;toggle()};main.querySelector('.delete').onclick=e=>{e.stopPropagation();deleteGroup(g)}})}
const original=window.renderGrupos;window.renderGrupos=function(rows){if(original)original(rows);setTimeout(()=>renderEnhanced(rows).catch(e=>{console.error(e);}),0)};
setTimeout(()=>{if(typeof groups!=='undefined')renderEnhanced(groups).catch(console.error)},600);
})();