(function(){
const css=`<style id="profEtapasCss">
.schedule-note{margin:0 0 12px;padding:12px 14px;border-left:4px solid var(--gold);background:#fff8e8;border-radius:10px;color:#4c5c64;font-size:.82rem}
.schedule-grid{display:grid;gap:10px}.schedule-row{display:grid;grid-template-columns:46px 1.35fr .78fr .9fr .78fr 1fr auto;gap:10px;align-items:end;border:1px solid var(--line);border-radius:12px;padding:12px}.schedule-row input,.schedule-row select{width:100%;padding:7px;border:1px solid var(--line);border-radius:8px;background:#fff}.schedule-row .muted{color:var(--muted);font-size:.68rem;margin-bottom:4px}.schedule-actions{display:flex;gap:6px;flex-wrap:wrap;align-items:center}.schedule-actions .btn{white-space:nowrap}@media(max-width:1050px){.schedule-row{grid-template-columns:46px 1fr 1fr}.schedule-row>*:nth-child(n+4){grid-column:auto}}@media(max-width:760px){.schedule-row{grid-template-columns:42px 1fr}.schedule-row>*:nth-child(n+3){grid-column:2}}</style>`;
if(!document.getElementById('profEtapasCss'))document.head.insertAdjacentHTML('beforeend',css);
const val=d=>d||'';
function addTab(){const tabs=document.querySelector('.tabs');if(!tabs||document.querySelector('[data-tab="cronograma"]'))return;const b=document.createElement('button');b.className='btn';b.dataset.tab='cronograma';b.textContent='Cronograma';tabs.appendChild(b);const host=tabs.parentElement;const pane=document.createElement('div');pane.id='cronograma';pane.className='tabpane hidden';pane.innerHTML='<div class="schedule-note"><b>Regra de prazo:</b> o professor pode alterar as datas a qualquer momento. A data “Correções até” marca o limite recomendado para a primeira versão com possibilidade de devolutiva e reenvio. O “Prazo final” encerra todos os envios, salvo nova liberação ou alteração feita pelo professor.</div><div class="schedule-grid" id="scheduleGrid"><div class="empty">Carregando cronograma...</div></div>';host.appendChild(pane);b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tabpane').forEach(x=>x.classList.add('hidden'));pane.classList.remove('hidden');renderSchedule()}}
async function renderSchedule(){const box=document.getElementById('scheduleGrid');if(!box)return;const {data,error}=await sb.from('etapas').select('*').eq('ativa',true).order('ordem');if(error){box.innerHTML='<div class="empty">'+esc(error.message)+'</div>';return}box.innerHTML=data.map((e,i)=>`<div class="schedule-row" data-row="${e.id}" data-manual="${e.liberada_manual?'1':'0'}"><div><b>${String(i+1).padStart(2,'0')}</b></div><div><b>${esc(e.nome)}</b><div class="muted">${esc(e.descricao||'')}</div></div><div><div class="muted">Início / liberação</div><input type="date" data-start="${e.id}" value="${val(e.data_inicio)}"></div><div><div class="muted">Correções até</div><input type="date" data-correction="${e.id}" value="${val(e.data_limite_correcao)}"></div><div><div class="muted">Prazo final</div><input type="date" data-end="${e.id}" value="${val(e.data_limite)}"></div><div><div class="muted">Liberação</div><select data-mode="${e.id}"><option value="AUTOMATICA" ${e.modo_liberacao==='AUTOMATICA'?'selected':''}>Automática pela data</option><option value="PROFESSOR" ${e.modo_liberacao==='PROFESSOR'?'selected':''}>Com anuência do professor</option></select></div><div class="schedule-actions"><button class="btn alt save-row" data-id="${e.id}">Salvar datas</button>${e.modo_liberacao==='PROFESSOR'?`<button class="btn ${e.liberada_manual?'warn':'ok'} toggle-release" data-id="${e.id}" data-state="${e.liberada_manual?'1':'0'}">${e.liberada_manual?'Bloquear':'Liberar'}</button>`:''}</div></div>`).join('');
box.querySelectorAll('.save-row').forEach(btn=>btn.onclick=async()=>{const id=btn.dataset.id,row=box.querySelector(`[data-row="${id}"]`),mode=box.querySelector(`[data-mode="${id}"]`).value,start=box.querySelector(`[data-start="${id}"]`).value||null,correction=box.querySelector(`[data-correction="${id}"]`).value||null,end=box.querySelector(`[data-end="${id}"]`).value||null,manual=row?.dataset.manual==='1';btn.disabled=true;const {error}=await sb.rpc('professor_atualizar_cronograma_etapa',{p_etapa_id:id,p_data_inicio:start,p_data_limite_correcao:correction,p_data_limite:end,p_modo:mode,p_liberada:manual});btn.disabled=false;if(error)return alert(error.message);alert('Cronograma atualizado.');await renderSchedule()});
box.querySelectorAll('.toggle-release').forEach(btn=>btn.onclick=async()=>{const id=btn.dataset.id,state=btn.dataset.state==='1',start=box.querySelector(`[data-start="${id}"]`).value||null,correction=box.querySelector(`[data-correction="${id}"]`).value||null,end=box.querySelector(`[data-end="${id}"]`).value||null;btn.disabled=true;const {error}=await sb.rpc('professor_atualizar_cronograma_etapa',{p_etapa_id:id,p_data_inicio:start,p_data_limite_correcao:correction,p_data_limite:end,p_modo:'PROFESSOR',p_liberada:!state});btn.disabled=false;if(error)return alert(error.message);await renderSchedule()})}
addTab();
const oldLoadAll=window.loadAll;if(oldLoadAll)window.loadAll=async function(){const r=await oldLoadAll.apply(this,arguments);if(!document.getElementById('cronograma')?.classList.contains('hidden'))await renderSchedule();return r};
})();
